name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install and Build
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: built
          FOLDER: _site
          CLEAN: true
